version: "2"
services:
  backup-service:
#    restart: always
    build: .
    ports:
      - "8000:8000"
    links:
      - mongo
  mongo:
    image: mongo:4.2
    volumes:
      - data-mongodb:/data/db

volumes:
  data-mongodb: