version: "2"
services:
  backup-service:
    container_name: backup-service
#    restart: always
    build: .
    ports:
      - "8000:8000"
    links:
      - mongo
  mongo:
    container_name: mongo
    image: mongo
    volumes:
      - ./data:/data/db
    ports:
      - "27017:27017"